### PR TITLE
Make timezone label default to timezone name

### PR DESCRIPTION
**Pull request by santipalenque**
https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskProject&view=vertical&task=2813991&fileview=grid

### CODE REVIEW

**Comment by smarcet** [comment]
@santipalenque i do think that we need to add an asterik
here
https://github.com/fntechgit/summit-admin/blob/e6963169b2291feaa1d3c62fd5ac0922b7d84217/src/components/forms/summit-form.js#L480
regards

**Review by smarcet — CHANGES_REQUESTED** [review]
please review comments

**Comment by santipalenque** [comment]
done @smarcet

**Review by smarcet — APPROVED** [review]
looks good to me

**Pull request merged**
